export default function Disclaimer() {
  return (
    <div className="disclaimer">
      <p>
        This tool provides AI-assisted hiring and positioning feedback based on resume content, role targeting, and common hiring patterns. It is designed for career insight and strategic self-positioning. Not guaranteed hiring outcomes. Results are generated by an AI model and should be considered alongside professional advice.
      </p>
    </div>
  )
}
