import { motion } from 'framer-motion'
import LandingNav from './landing/LandingNav'
import LandingFooter from './landing/LandingFooter'

export default function TermsPage({ onNavigate }) {
  return (
    <motion.div
      key="terms"
      className="lp-faq-page"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.35 }}
    >
      <LandingNav onNavigate={onNavigate} />

      {/* Purple hero header */}
      <div className="lp-faq-hero">
        <span className="lp-section-tag lp-section-tag--gold">✦ legal</span>
        <h1 className="lp-faq-hero__title">Terms &amp; Conditions</h1>
      </div>

      {/* Cream body */}
      <div className="lp-faq-body">
        <div className="lp-faq-body__inner lp-terms">

          <p className="lp-terms__meta">Roast My Resume by NURHR &mdash; Last updated: June 2026</p>

          <div className="lp-terms__section">
            <h2>1. Acceptance of Terms</h2>
            <p>By accessing or using Roast My Resume you agree to be bound by these Terms and Conditions. If you do not agree, please do not use the service.</p>
          </div>

          <div className="lp-terms__section">
            <h2>2. About the Service</h2>
            <p>Roast My Resume provides AI-powered resume and LinkedIn profile analysis. Results represent perception-based feedback drawn from HR expertise and are not guaranteed hiring outcomes. This service is not a recruitment agency, career counselling service, or provider of professional legal or financial advice.</p>
          </div>

          <div className="lp-terms__section">
            <h2>3. Data Collection and Storage</h2>
            <p>By using Roast My Resume you agree to the following:</p>
            <ul>
              <li>Your resume content is processed solely to generate your analysis</li>
              <li>Your analysis results are stored securely for 90 days from the date of purchase</li>
              <li>Your email address is collected at checkout and used to deliver your results</li>
              <li>Your data is never sold, shared, or used for advertising purposes</li>
              <li>After 90 days your results are permanently deleted from our systems</li>
            </ul>
          </div>

          <div className="lp-terms__section">
            <h2>4. Your Rights</h2>
            <p>You have the right to:</p>
            <ul>
              <li>Request access to the data we hold about you</li>
              <li>Request deletion of your data at any time before the 90 day period</li>
              <li>Withdraw consent for data storage at any time</li>
            </ul>
            <p>To exercise any of these rights email <a href="mailto:farzana@noturregularhr.com">farzana@noturregularhr.com</a></p>
          </div>

          <div className="lp-terms__section">
            <h2>5. Payment and Refunds</h2>
            <ul>
              <li>All payments are processed securely via Stripe</li>
              <li>Beta pricing is subject to change without notice</li>
              <li>All sales are final. Due to the nature of digital services, we do not offer refunds once your analysis has been generated</li>
              <li>If you experience a technical issue that prevents you from receiving your results, please contact <a href="mailto:farzana@noturregularhr.com">farzana@noturregularhr.com</a> and we will resolve it</li>
            </ul>
          </div>

          <div className="lp-terms__section">
            <h2>6. Intellectual Property</h2>
            <p>All content, copy, methodology, brand assets, and software including Roast My Resume and NURHR are owned by NURHR and protected under applicable copyright law. &copy; 2026 NURHR. You may not reproduce, redistribute, or repurpose any content without written permission.</p>
          </div>

          <div className="lp-terms__section">
            <h2>7. Disclaimer</h2>
            <p>Roast My Resume is provided as is. While we take care to deliver accurate and useful analysis, NURHR makes no guarantee that implementing feedback will result in employment, interviews, or any specific career outcome. Results are perception-based and generated by AI informed by HR expertise.</p>
          </div>

          <div className="lp-terms__section">
            <h2>8. Limitation of Liability</h2>
            <p>To the fullest extent permitted by law, NURHR is not liable for any direct, indirect, or consequential loss arising from use of this service, reliance on results, or any employment or career decisions made based on the analysis provided.</p>
          </div>

          <div className="lp-terms__section">
            <h2>9. Changes to These Terms</h2>
            <p>We may update these terms at any time. The date at the top of this page reflects the most recent update. Continued use of the service following any changes constitutes acceptance of the updated terms.</p>
          </div>

          <div className="lp-terms__section">
            <h2>10. Governing Law</h2>
            <p>These terms are governed by the laws of New South Wales, Australia.</p>
          </div>

          <div className="lp-terms__section">
            <h2>11. Contact</h2>
            <p>For any questions regarding these terms email <a href="mailto:farzana@noturregularhr.com">farzana@noturregularhr.com</a></p>
          </div>

        </div>
      </div>

      <LandingFooter onNavigate={onNavigate} />
    </motion.div>
  )
}
