// ── Industries ────────────────────────────────────────────────────────────────
export const INDUSTRIES = [
  'Accounting & Audit',
  'Advertising & Media',
  'Aged Care & Disability Services',
  'Agriculture & Agribusiness',
  'Architecture & Urban Planning',
  'Arts & Entertainment',
  'Aviation & Aerospace',
  'Banking & Financial Services',
  'Biotechnology & Life Sciences',
  'Construction & Infrastructure',
  'Consulting & Professional Services',
  'Defence & National Security',
  'E-commerce & Marketplaces',
  'Education & Training',
  'Energy & Utilities',
  'Engineering (Civil, Structural, Mechanical)',
  'Environment & Sustainability',
  'Fashion & Apparel',
  'FMCG & Consumer Goods',
  'Food & Beverage',
  'Government & Public Sector',
  'Health Insurance & Private Health',
  'Healthcare & Medical',
  'Hospitality & Events',
  'HR & People & Culture',
  'Insurance (General & Life)',
  'Legal Services',
  'Logistics & Supply Chain',
  'Manufacturing & Industrial',
  'Media & Publishing',
  'Mining & Resources',
  'NFP & Social Impact',
  'Pharmaceutical & Drug Development',
  'Private Equity & Venture Capital',
  'Property & Real Estate',
  'Public Relations & Communications',
  'Recruitment & Staffing',
  'Retail (Bricks & Mortar)',
  'Risk & Compliance',
  'Sales & Business Development',
  'Sports & Recreation',
  'Superannuation & Wealth Management',
  'Technology & SaaS',
  'Telecommunications',
  'Tourism & Travel',
  'Transport & Infrastructure',
  'Veterinary & Animal Health',
  'Wholesale & Distribution',
  'Other',
]

// ── Generic departments (fallback for industries without a specific mapping) ──
const GENERIC_DEPARTMENTS = [
  'Business Development',
  'Corporate Affairs',
  'Customer Experience',
  'Data & Analytics',
  'Executive & Leadership',
  'Finance & Accounting',
  'HR & People & Culture',
  'IT & Technology',
  'Legal & Compliance',
  'Marketing & Communications',
  'Operations',
  'Product',
  'Project Management',
  'Risk & Audit',
  'Sales',
  'Strategy & Transformation',
]

// ── Industry → Department mappings ───────────────────────────────────────────
const INDUSTRY_DEPARTMENTS = {
  'Technology & SaaS': [
    'Backend Engineering',
    'Cloud & Infrastructure',
    'Customer Success',
    'Data & AI',
    'Design & UX',
    'DevOps & Platform',
    'Engineering Leadership',
    'Frontend Engineering',
    'Mobile Engineering',
    'Product Management',
    'QA & Testing',
    'Sales & Partnerships',
    'Security Engineering',
    'Solutions Engineering',
  ],
  'Banking & Financial Services': [
    'Commercial Banking',
    'Compliance & Regulatory',
    'Corporate Banking',
    'Credit & Lending',
    'Data & Analytics',
    'Finance & Treasury',
    'HR & People',
    'Institutional Banking',
    'Investment Banking',
    'Marketing',
    'Operations & Settlements',
    'Private Banking',
    'Retail Banking',
    'Risk Management',
    'Technology & Digital',
  ],
  'Healthcare & Medical': [
    'Allied Health',
    'Clinical Nursing',
    'Clinical Operations',
    'Dental',
    'Diagnostics & Pathology',
    'Executive & Leadership',
    'GP & General Practice',
    'Healthcare Administration',
    'HR & Workforce',
    'IT & Digital Health',
    'Mental Health',
    'Pharmacy',
    'Radiology & Imaging',
    'Specialist Medicine',
    'Surgical',
  ],
  'Hospitality & Events': [
    'Bar & Beverage',
    'Catering & Banqueting',
    'Conference & Events',
    'Executive Leadership',
    'Food & Beverage Management',
    'Front Office',
    'Guest Experience',
    'Housekeeping & Facilities',
    'HR & People',
    'Kitchen & Culinary',
    'Marketing & Revenue',
    'Reservations & Revenue',
    'Venue Operations',
  ],
  'Construction & Infrastructure': [
    'Architecture',
    'Building Services',
    'Contracts & Procurement',
    'Design & Engineering',
    'EHS & Safety',
    'Estimating & Quantity Surveying',
    'HSEQ',
    'Project Management',
    'Site Operations',
    'Structural Engineering',
    'Urban Planning',
  ],
  'Government & Public Sector': [
    'Community Services',
    'Corporate Services',
    'Defence & Security',
    'Economic Development',
    'Executive & Leadership',
    'ICT & Digital',
    'Legal & Compliance',
    'Parks & Environment',
    'People & Capability',
    'Policy & Strategy',
    'Procurement',
    'Program Delivery',
    'Public Relations & Communications',
  ],
  'Education & Training': [
    'Administration',
    'Curriculum & Learning Design',
    'Early Childhood',
    'Executive Leadership',
    'Finance & Operations',
    'HR & People',
    'ICT',
    'Library & Resources',
    'Marketing & Enrolments',
    'Primary Education',
    'Secondary Education',
    'Special Education',
    'Tertiary & Higher Education',
    'Vocational & TAFE',
  ],
  'Retail (Bricks & Mortar)': [
    'Buying & Merchandising',
    'Customer Service',
    'E-commerce',
    'Finance',
    'HR & People',
    'Loss Prevention',
    'Marketing',
    'Operations & Logistics',
    'Store Management',
    'Visual Merchandising',
    'Wholesale & Supply',
  ],
  'Mining & Resources': [
    'Community & Social Performance',
    'Environment & Sustainability',
    'Exploration & Geology',
    'Finance & Commercial',
    'HR & Industrial Relations',
    'HSE',
    'Maintenance & Reliability',
    'Mine Planning',
    'Operations',
    'Processing & Metallurgy',
    'Projects & Capital',
  ],
  'NFP & Social Impact': [
    'Advocacy & Policy',
    'Community Programs',
    'Events & Fundraising',
    'Finance & Operations',
    'Fundraising & Development',
    'Governance & Board',
    'HR & People',
    'Marketing & Communications',
    'Programs & Delivery',
    'Research & Evaluation',
    'Volunteer Management',
  ],
  'Aged Care & Disability Services': [
    'Care Coordination',
    'Carers & Personal Support',
    'Clinical Governance',
    'Community Access',
    'Corporate & Compliance',
    'HR & Workforce',
    'Nursing & Clinical',
    'Operations & Administration',
    'Quality & Safety',
    'SIL & Supported Living',
  ],
  'Property & Real Estate': [
    'Asset Management',
    'Body Corporate & Strata',
    'Commercial Agency',
    'Development & Projects',
    'Finance & Commercial',
    'Investment & Acquisitions',
    'Operations',
    'Property Management',
    'Residential Agency',
    'Retail Leasing',
    'Valuation',
  ],
  'Insurance (General & Life)': [
    'Actuarial',
    'Claims',
    'Commercial Insurance',
    'Finance & Reporting',
    'IT & Digital',
    'Legal & Compliance',
    'Marketing',
    'Personal Insurance',
    'Product & Pricing',
    'Risk & Compliance',
    'Underwriting',
  ],
  'Logistics & Supply Chain': [
    'Customer Service',
    'Data & Reporting',
    'Fleet & Transport',
    'HR & People',
    'Import/Export & Customs',
    'IT & Systems',
    'Operations',
    'Procurement & Sourcing',
    'Supply Planning',
    'Warehouse & Distribution',
  ],
  'Legal Services': [
    'Administrative Support',
    'Clerking & Paralegal',
    'Commercial Law',
    'Construction & Infrastructure Law',
    'Corporate & M&A',
    'Employment Law',
    'Family Law',
    'Finance & Operations',
    'HR & People',
    'Intellectual Property',
    'Litigation & Dispute Resolution',
    'Privacy & Regulatory',
  ],
  'Recruitment & Staffing': [
    'Back Office & Payroll',
    'Business Development',
    'Client Management',
    'Executive Search',
    'HR & People',
    'Onboarding & Compliance',
    'Permanent Placement',
    'Talent Research',
    'Technology Recruitment',
    'Temporary & Contract',
  ],
  'E-commerce & Marketplaces': [
    'Customer Experience',
    'Data & Analytics',
    'Digital Marketing',
    'Finance & Commercial',
    'HR & People',
    'Operations & Fulfillment',
    'Product & Technology',
    'Seller/Vendor Management',
    'UX & Design',
  ],
  'Manufacturing & Industrial': [
    'Business Development',
    'EHS',
    'Engineering',
    'Finance',
    'HR & Industrial Relations',
    'Maintenance & Reliability',
    'Operations',
    'Planning & Scheduling',
    'Process Improvement',
    'Procurement & Supply Chain',
    'Quality Assurance',
  ],
  'Food & Beverage': [
    'Business Development',
    'Engineering & Maintenance',
    'Finance',
    'Food Science & Innovation',
    'HR & People',
    'Marketing',
    'Operations',
    'Procurement & Supply',
    'Quality & Food Safety',
    'Regulatory & Compliance',
  ],
  'Pharmaceutical & Drug Development': [
    'Clinical Affairs',
    'Clinical Research',
    'Drug Safety & Pharmacovigilance',
    'Finance & Accounting',
    'HR & People',
    'IT & Data',
    'Medical Affairs',
    'Operations & Manufacturing',
    'Quality Assurance',
    'Regulatory Affairs',
    'Sales & Marketing',
  ],
}

// ── Role sets (reusable) ──────────────────────────────────────────────────────
const R = {
  engineering: [
    'Graduate / Junior Software Engineer',
    'Software Engineer',
    'Senior Software Engineer',
    'Staff Engineer',
    'Principal Engineer',
    'Engineering Manager',
    'Director of Engineering',
    'VP of Engineering',
    'CTO',
    'Other / Describe my role',
  ],
  product: [
    'Associate Product Manager',
    'Product Manager',
    'Senior Product Manager',
    'Principal Product Manager',
    'Group Product Manager',
    'Head of Product',
    'Director of Product',
    'VP of Product',
    'Chief Product Officer',
    'Other / Describe my role',
  ],
  design: [
    'Junior Designer',
    'UX Designer',
    'UI Designer',
    'Product Designer',
    'Senior Product Designer',
    'UX Researcher',
    'Lead Designer',
    'Head of Design',
    'Other / Describe my role',
  ],
  data: [
    'Data Analyst',
    'Senior Data Analyst',
    'Data Scientist',
    'Senior Data Scientist',
    'Data Engineer',
    'Analytics Engineer',
    'ML Engineer',
    'Head of Data & Analytics',
    'Chief Data Officer',
    'Other / Describe my role',
  ],
  devops: [
    'DevOps Engineer',
    'Site Reliability Engineer',
    'Platform Engineer',
    'Cloud Engineer',
    'Cloud Architect',
    'Infrastructure Engineer',
    'Head of Infrastructure',
    'Other / Describe my role',
  ],
  security: [
    'Security Analyst',
    'Security Engineer',
    'Penetration Tester',
    'Application Security Engineer',
    'Security Architect',
    'Head of Security',
    'CISO',
    'Other / Describe my role',
  ],
  marketing: [
    'Marketing Coordinator',
    'Marketing Manager',
    'Senior Marketing Manager',
    'Digital Marketing Manager',
    'Content Manager',
    'Brand Manager',
    'Growth Manager',
    'Head of Marketing',
    'Marketing Director',
    'CMO',
    'Other / Describe my role',
  ],
  sales: [
    'Sales Representative / BDR',
    'Account Executive',
    'Senior Account Executive',
    'Business Development Manager',
    'Sales Manager',
    'Head of Sales',
    'Sales Director',
    'VP of Sales',
    'Chief Revenue Officer',
    'Other / Describe my role',
  ],
  customer_success: [
    'Customer Success Manager',
    'Senior Customer Success Manager',
    'Customer Success Lead',
    'Head of Customer Success',
    'Customer Experience Manager',
    'Director of Customer Success',
    'Other / Describe my role',
  ],
  hr_people: [
    'HR Coordinator',
    'HR Advisor',
    'HR Business Partner',
    'Senior HR Business Partner',
    'People & Culture Manager',
    'Head of HR',
    'HR Director',
    'Chief People Officer',
    'L&D Manager',
    'Head of L&D',
    'Other / Describe my role',
  ],
  talent: [
    'Recruitment Coordinator',
    'Talent Acquisition Partner',
    'Senior Talent Acquisition Partner',
    'Recruitment Manager',
    'Head of Talent Acquisition',
    'Talent Director',
    'Other / Describe my role',
  ],
  finance: [
    'Finance Analyst',
    'Senior Finance Analyst',
    'Finance Manager',
    'Senior Finance Manager',
    'Financial Controller',
    'FP&A Manager',
    'Head of Finance',
    'CFO',
    'Other / Describe my role',
  ],
  accounting: [
    'Graduate Accountant',
    'Accountant',
    'Senior Accountant',
    'Management Accountant',
    'Financial Accountant',
    'Audit Manager',
    'Finance Manager',
    'Financial Controller',
    'CFO',
    'Other / Describe my role',
  ],
  legal: [
    'Paralegal / Law Clerk',
    'Graduate Lawyer',
    'Solicitor',
    'Senior Solicitor',
    'Associate',
    'Senior Associate',
    'Special Counsel',
    'Partner',
    'In-House Counsel',
    'General Counsel',
    'Other / Describe my role',
  ],
  operations: [
    'Operations Coordinator',
    'Operations Analyst',
    'Operations Manager',
    'Senior Operations Manager',
    'Head of Operations',
    'Director of Operations',
    'COO',
    'General Manager',
    'Other / Describe my role',
  ],
  executive: [
    'General Manager',
    'Director',
    'Managing Director',
    'CEO',
    'COO',
    'CFO',
    'CTO',
    'CMO',
    'Chief People Officer',
    'Other / Describe my role',
  ],
  clinical: [
    'Enrolled Nurse',
    'Registered Nurse',
    'Clinical Nurse Specialist',
    'Clinical Nurse Educator',
    'ANUM / NUM',
    'Nurse Manager',
    'Director of Nursing',
    'Allied Health Professional',
    'Clinical Manager',
    'Director of Clinical Services',
    'Other / Describe my role',
  ],
  doctor: [
    'Junior Medical Officer',
    'Registrar',
    'Specialist / Consultant',
    'Senior Specialist',
    'Director of Medical Services',
    'Other / Describe my role',
  ],
  education_role: [
    'Early Childhood Educator',
    'Teacher',
    'Leading Teacher / Senior Teacher',
    'Head of Department / Learning Area',
    'Deputy Principal / Vice Principal',
    'Principal',
    'Learning Designer / Instructional Designer',
    'Curriculum Developer',
    'Lecturer / Academic',
    'Senior Lecturer',
    'Other / Describe my role',
  ],
  construction_pm: [
    'Graduate Engineer',
    'Site Engineer',
    'Project Engineer',
    'Project Manager',
    'Senior Project Manager',
    'Contracts Manager',
    'Site Manager',
    'Construction Manager',
    'Project Director',
    'Other / Describe my role',
  ],
  qty_surveying: [
    'Graduate Quantity Surveyor',
    'Quantity Surveyor',
    'Senior Quantity Surveyor',
    'Lead Quantity Surveyor',
    'Estimator',
    'Senior Estimator',
    'Head of Commercial',
    'Other / Describe my role',
  ],
  hse: [
    'WHS Officer / Safety Officer',
    'WHS Advisor',
    'Safety Manager',
    'WHS Manager',
    'HSE Manager',
    'Head of Safety',
    'Group HSE Manager',
    'Other / Describe my role',
  ],
  hospitality_role: [
    'Team Leader / Supervisor',
    'Duty Manager',
    'Department Manager',
    'Assistant Manager',
    'Operations Manager',
    'Food & Beverage Manager',
    'Front Office Manager',
    'Revenue Manager',
    'General Manager',
    'Other / Describe my role',
  ],
  events: [
    'Events Coordinator',
    'Events Manager',
    'Senior Events Manager',
    'Head of Events',
    'Director of Events',
    'Other / Describe my role',
  ],
  property_role: [
    'Property Officer',
    'Property Manager',
    'Senior Property Manager',
    'Leasing Consultant',
    'Business Development Manager',
    'Residential Sales Agent',
    'Commercial Sales / Leasing Agent',
    'Asset Manager',
    'Portfolio Manager',
    'Development Manager',
    'Head of Property',
    'Other / Describe my role',
  ],
  government_role: [
    'Policy Officer / Analyst',
    'Senior Policy Officer',
    'Project Officer',
    'Program Manager',
    'Director',
    'Executive Director',
    'Deputy Secretary / Deputy CEO',
    'Secretary / CEO',
    'Other / Describe my role',
  ],
  consulting_role: [
    'Analyst',
    'Consultant',
    'Senior Consultant',
    'Manager',
    'Senior Manager',
    'Principal',
    'Associate Director',
    'Director',
    'Partner',
    'Other / Describe my role',
  ],
  nfp_role: [
    'Program Officer / Coordinator',
    'Program Manager',
    'Community Development Manager',
    'Fundraising Manager',
    'Policy Officer',
    'Marketing Manager',
    'Operations Manager',
    'CEO',
    'Other / Describe my role',
  ],
  care_role: [
    'Support Worker',
    'Senior Support Worker',
    'Team Leader / Coordinator',
    'Care Coordinator',
    'Case Manager',
    'Service Manager',
    'Registered Nurse',
    'Other / Describe my role',
  ],
  geology: [
    'Graduate Geologist',
    'Geologist',
    'Senior Geologist',
    'Principal Geologist',
    'Chief Geologist',
    'Mine Geologist',
    'Other / Describe my role',
  ],
  maintenance: [
    'Maintenance Technician / Tradesperson',
    'Maintenance Planner',
    'Reliability Engineer',
    'Maintenance Engineer',
    'Maintenance Supervisor',
    'Maintenance Manager',
    'Head of Maintenance',
    'Other / Describe my role',
  ],
  qa: [
    'QA Officer / Analyst',
    'Senior QA Analyst',
    'QA Engineer',
    'Test Automation Engineer',
    'QA Lead',
    'QA Manager',
    'Head of Quality',
    'Other / Describe my role',
  ],
  procurement: [
    'Procurement Analyst / Officer',
    'Category Manager',
    'Procurement Manager',
    'Senior Procurement Manager',
    'Supply Chain Manager',
    'Head of Procurement',
    'Chief Procurement Officer',
    'Other / Describe my role',
  ],
  actuarial: [
    'Actuarial Analyst',
    'Actuary',
    'Senior Actuary',
    'Principal Actuary',
    'Consulting Actuary',
    'Head of Actuarial',
    'Other / Describe my role',
  ],
  underwriting: [
    'Underwriting Assistant',
    'Underwriter',
    'Senior Underwriter',
    'Underwriting Manager',
    'Head of Underwriting',
    'Other / Describe my role',
  ],
  claims: [
    'Claims Officer',
    'Claims Assessor',
    'Senior Claims Assessor',
    'Claims Manager',
    'Head of Claims',
    'Other / Describe my role',
  ],
  clinical_research: [
    'Clinical Research Associate',
    'Senior CRA',
    'Clinical Research Manager',
    'Clinical Affairs Manager',
    'Medical Monitor',
    'Head of Clinical Affairs',
    'Other / Describe my role',
  ],
  regulatory: [
    'Regulatory Affairs Officer',
    'Regulatory Affairs Specialist',
    'Regulatory Affairs Manager',
    'Head of Regulatory Affairs',
    'VP Regulatory Affairs',
    'Other / Describe my role',
  ],
  pharmacy: [
    'Pharmacy Assistant',
    'Pharmacist',
    'Senior Pharmacist',
    'Pharmacy Manager',
    'Clinical Pharmacist',
    'Head of Pharmacy',
    'Other / Describe my role',
  ],
  it_generic: [
    'IT Support / Helpdesk',
    'Systems Administrator',
    'IT Project Manager',
    'IT Manager',
    'Head of IT',
    'IT Director',
    'CTO / CIO',
    'Other / Describe my role',
  ],
  generic: [
    'Coordinator / Administrator',
    'Analyst',
    'Manager',
    'Senior Manager',
    'Head of Function',
    'Director',
    'Vice President',
    'C-Suite Executive',
    'Other / Describe my role',
  ],
}

// ── Department → Roles mapping ────────────────────────────────────────────────
const DEPARTMENT_ROLES = {
  // Technology & SaaS
  'Backend Engineering': R.engineering,
  'Frontend Engineering': R.engineering,
  'Mobile Engineering': R.engineering,
  'Engineering Leadership': R.engineering,
  'Cloud & Infrastructure': R.devops,
  'DevOps & Platform': R.devops,
  'Security Engineering': R.security,
  'QA & Testing': R.qa,
  'Data & AI': R.data,
  'Design & UX': R.design,
  'Product Management': R.product,
  'Customer Success': R.customer_success,
  'Sales & Partnerships': R.sales,
  'Solutions Engineering': [
    'Solutions Engineer',
    'Senior Solutions Engineer',
    'Solutions Architect',
    'Principal Solutions Architect',
    'Head of Solutions Engineering',
    'Other / Describe my role',
  ],

  // Banking & Financial Services
  'Commercial Banking': R.generic,
  'Compliance & Regulatory': [
    'Compliance Analyst',
    'Compliance Manager',
    'Senior Compliance Manager',
    'Head of Compliance',
    'Chief Compliance Officer',
    'Other / Describe my role',
  ],
  'Corporate Banking': R.generic,
  'Credit & Lending': [
    'Credit Analyst',
    'Senior Credit Analyst',
    'Credit Manager',
    'Head of Credit',
    'Other / Describe my role',
  ],
  'Data & Analytics': R.data,
  'Finance & Treasury': R.finance,
  'HR & People': R.hr_people,
  'Institutional Banking': R.generic,
  'Investment Banking': [
    'Analyst',
    'Associate',
    'Vice President',
    'Director',
    'Managing Director',
    'Other / Describe my role',
  ],
  'Marketing': R.marketing,
  'Operations & Settlements': R.operations,
  'Private Banking': R.generic,
  'Retail Banking': R.generic,
  'Risk Management': [
    'Risk Analyst',
    'Senior Risk Analyst',
    'Risk Manager',
    'Head of Risk',
    'Chief Risk Officer',
    'Other / Describe my role',
  ],
  'Technology & Digital': R.it_generic,

  // Healthcare & Medical
  'Allied Health': [
    'Physiotherapist',
    'Occupational Therapist',
    'Speech Pathologist',
    'Dietitian',
    'Social Worker',
    'Senior Allied Health Professional',
    'Allied Health Manager',
    'Other / Describe my role',
  ],
  'Clinical Nursing': R.clinical,
  'Clinical Operations': R.operations,
  'Dental': [
    'Dental Assistant',
    'Dental Therapist',
    'Dental Hygienist',
    'Dentist',
    'Senior Dentist',
    'Dental Practice Manager',
    'Other / Describe my role',
  ],
  'Diagnostics & Pathology': [
    'Medical Scientist',
    'Senior Medical Scientist',
    'Laboratory Manager',
    'Pathologist',
    'Other / Describe my role',
  ],
  'Executive & Leadership': R.executive,
  'GP & General Practice': R.doctor,
  'Healthcare Administration': R.operations,
  'HR & Workforce': R.hr_people,
  'IT & Digital Health': R.it_generic,
  'Mental Health': [
    'Mental Health Clinician',
    'Psychologist',
    'Senior Psychologist',
    'Mental Health Nurse',
    'Clinical Psychologist',
    'Mental Health Team Leader',
    'Director of Mental Health',
    'Other / Describe my role',
  ],
  'Pharmacy': R.pharmacy,
  'Radiology & Imaging': [
    'Radiographer',
    'Senior Radiographer',
    'Sonographer',
    'Radiologist',
    'Radiology Manager',
    'Other / Describe my role',
  ],
  'Specialist Medicine': R.doctor,
  'Surgical': R.doctor,

  // Hospitality & Events
  'Bar & Beverage': R.hospitality_role,
  'Catering & Banqueting': R.hospitality_role,
  'Conference & Events': R.events,
  'Executive Leadership': R.executive,
  'Food & Beverage Management': R.hospitality_role,
  'Front Office': R.hospitality_role,
  'Guest Experience': R.customer_success,
  'Housekeeping & Facilities': R.hospitality_role,
  'Kitchen & Culinary': [
    'Commis Chef',
    'Chef de Partie',
    'Sous Chef',
    'Head Chef',
    'Executive Chef',
    'Other / Describe my role',
  ],
  'Marketing & Revenue': R.marketing,
  'Reservations & Revenue': [
    'Reservations Agent',
    'Revenue Analyst',
    'Revenue Manager',
    'Director of Revenue',
    'Other / Describe my role',
  ],
  'Venue Operations': R.operations,

  // Construction & Infrastructure
  'Architecture': [
    'Graduate Architect',
    'Architectural Technician',
    'Architect',
    'Project Architect',
    'Associate Architect',
    'Principal Architect',
    'Director of Architecture',
    'Other / Describe my role',
  ],
  'Building Services': R.construction_pm,
  'Contracts & Procurement': [
    'Contracts Administrator',
    'Senior Contracts Administrator',
    'Contracts Manager',
    'Senior Contracts Manager',
    'Head of Contracts',
    'Other / Describe my role',
  ],
  'Design & Engineering': R.construction_pm,
  'EHS & Safety': R.hse,
  'Estimating & Quantity Surveying': R.qty_surveying,
  'HSEQ': R.hse,
  'Project Management': R.construction_pm,
  'Site Operations': R.construction_pm,
  'Structural Engineering': [
    'Graduate Structural Engineer',
    'Structural Engineer',
    'Senior Structural Engineer',
    'Principal Structural Engineer',
    'Associate Director',
    'Director',
    'Other / Describe my role',
  ],
  'Urban Planning': [
    'Graduate Planner',
    'Town Planner',
    'Senior Planner',
    'Principal Planner',
    'Planning Manager',
    'Director of Planning',
    'Other / Describe my role',
  ],

  // Government & Public Sector
  'Community Services': R.nfp_role,
  'Corporate Services': R.operations,
  'Defence & Security': R.government_role,
  'Economic Development': R.government_role,
  'ICT & Digital': R.it_generic,
  'Legal & Compliance': R.legal,
  'Parks & Environment': R.government_role,
  'People & Capability': R.hr_people,
  'Policy & Strategy': R.government_role,
  'Procurement': R.procurement,
  'Program Delivery': R.government_role,
  'Public Relations & Communications': R.marketing,

  // Education & Training
  'Administration': [
    'Receptionist / Office Assistant',
    'School Administrator',
    'Senior Administrator',
    'Office Manager',
    'Executive Assistant',
    'Operations Manager',
    'Other / Describe my role',
  ],
  'Curriculum & Learning Design': R.education_role,
  'Early Childhood': R.education_role,
  'Finance & Operations': R.finance,
  'ICT': R.it_generic,
  'Library & Resources': [
    'Library Technician',
    'Librarian',
    'Senior Librarian',
    'Library Manager',
    'Other / Describe my role',
  ],
  'Marketing & Enrolments': R.marketing,
  'Primary Education': R.education_role,
  'Secondary Education': R.education_role,
  'Special Education': R.education_role,
  'Tertiary & Higher Education': R.education_role,
  'Vocational & TAFE': R.education_role,

  // Retail
  'Buying & Merchandising': [
    'Buyer\'s Assistant',
    'Assistant Buyer',
    'Buyer',
    'Senior Buyer',
    'Merchandiser',
    'Head of Buying',
    'Other / Describe my role',
  ],
  'Customer Service': R.customer_success,
  'E-commerce': R.product,
  'Finance': R.finance,
  'Loss Prevention': [
    'Loss Prevention Officer',
    'Senior Loss Prevention Officer',
    'Loss Prevention Manager',
    'Head of Loss Prevention',
    'Other / Describe my role',
  ],
  'Operations & Logistics': R.operations,
  'Store Management': [
    'Team Leader',
    'Assistant Store Manager',
    'Store Manager',
    'Area Manager',
    'State Manager',
    'Head of Retail Operations',
    'Other / Describe my role',
  ],
  'Visual Merchandising': [
    'Visual Merchandiser',
    'Senior Visual Merchandiser',
    'VM Lead',
    'National Visual Merchandising Manager',
    'Other / Describe my role',
  ],
  'Wholesale & Supply': R.procurement,

  // Mining & Resources
  'Community & Social Performance': R.nfp_role,
  'Environment & Sustainability': [
    'Environmental Officer',
    'Environmental Scientist',
    'Sustainability Analyst',
    'Sustainability Manager',
    'Head of Sustainability',
    'Other / Describe my role',
  ],
  'Exploration & Geology': R.geology,
  'Finance & Commercial': R.finance,
  'HR & Industrial Relations': R.hr_people,
  'HSE': R.hse,
  'Maintenance & Reliability': R.maintenance,
  'Mine Planning': R.construction_pm,
  'Operations': R.operations,
  'Processing & Metallurgy': [
    'Process Technician',
    'Metallurgist',
    'Senior Metallurgist',
    'Plant Metallurgist',
    'Processing Manager',
    'Other / Describe my role',
  ],
  'Projects & Capital': R.construction_pm,

  // NFP & Social Impact
  'Advocacy & Policy': R.government_role,
  'Community Programs': R.nfp_role,
  'Events & Fundraising': R.events,
  'Fundraising & Development': [
    'Fundraising Coordinator',
    'Fundraising Manager',
    'Major Gifts Manager',
    'Head of Fundraising',
    'Director of Fundraising & Development',
    'Other / Describe my role',
  ],
  'Governance & Board': R.executive,
  'Programs & Delivery': R.nfp_role,
  'Research & Evaluation': [
    'Research Officer',
    'Research Analyst',
    'Senior Research Officer',
    'Research Manager',
    'Other / Describe my role',
  ],
  'Volunteer Management': [
    'Volunteer Coordinator',
    'Volunteer Manager',
    'Head of Volunteering',
    'Other / Describe my role',
  ],

  // Aged Care & Disability Services
  'Care Coordination': R.care_role,
  'Carers & Personal Support': R.care_role,
  'Clinical Governance': R.clinical,
  'Community Access': R.care_role,
  'Corporate & Compliance': R.operations,
  'Nursing & Clinical': R.clinical,
  'Operations & Administration': R.operations,
  'Quality & Safety': [
    'Quality & Compliance Officer',
    'Quality Manager',
    'NDIS Quality & Safeguarding Coordinator',
    'Head of Quality',
    'Other / Describe my role',
  ],
  'SIL & Supported Living': R.care_role,

  // Property & Real Estate
  'Asset Management': R.property_role,
  'Body Corporate & Strata': [
    'Strata Manager',
    'Senior Strata Manager',
    'Portfolio Manager',
    'Head of Strata',
    'Other / Describe my role',
  ],
  'Commercial Agency': R.property_role,
  'Development & Projects': [
    'Development Analyst',
    'Development Manager',
    'Senior Development Manager',
    'Project Director',
    'Head of Development',
    'Other / Describe my role',
  ],
  'Investment & Acquisitions': [
    'Acquisitions Analyst',
    'Acquisitions Manager',
    'Investment Manager',
    'Head of Investments',
    'Other / Describe my role',
  ],
  'Property Management': R.property_role,
  'Residential Agency': R.property_role,
  'Retail Leasing': R.property_role,
  'Valuation': [
    'Graduate Valuer',
    'Valuer',
    'Senior Valuer',
    'Certified Practising Valuer',
    'Director of Valuation',
    'Other / Describe my role',
  ],

  // Insurance
  'Actuarial': R.actuarial,
  'Claims': R.claims,
  'Commercial Insurance': R.sales,
  'Finance & Reporting': R.finance,
  'IT & Digital': R.it_generic,
  'Personal Insurance': R.sales,
  'Product & Pricing': R.product,
  'Risk & Compliance': [
    'Risk Analyst',
    'Compliance Analyst',
    'Risk & Compliance Manager',
    'Head of Risk & Compliance',
    'Chief Risk Officer',
    'Other / Describe my role',
  ],
  'Underwriting': R.underwriting,

  // Logistics & Supply Chain
  'Data & Reporting': R.data,
  'Fleet & Transport': R.operations,
  'Import/Export & Customs': [
    'Customs Broker',
    'Import/Export Coordinator',
    'Trade Compliance Manager',
    'Head of Trade & Customs',
    'Other / Describe my role',
  ],
  'IT & Systems': R.it_generic,
  'Procurement & Sourcing': R.procurement,
  'Supply Planning': [
    'Supply Planner',
    'Demand Planner',
    'Senior Supply Planner',
    'Supply Chain Manager',
    'Head of Supply Chain',
    'Other / Describe my role',
  ],
  'Warehouse & Distribution': [
    'Warehouse Team Leader',
    'Warehouse Supervisor',
    'Warehouse Manager',
    'Distribution Manager',
    'Operations Manager',
    'Other / Describe my role',
  ],

  // Legal Services
  'Administrative Support': [
    'Legal Secretary',
    'Legal Administrator',
    'Practice Manager',
    'Other / Describe my role',
  ],
  'Clerking & Paralegal': R.legal,
  'Commercial Law': R.legal,
  'Construction & Infrastructure Law': R.legal,
  'Corporate & M&A': R.legal,
  'Employment Law': R.legal,
  'Family Law': R.legal,
  'Intellectual Property': R.legal,
  'Litigation & Dispute Resolution': R.legal,
  'Privacy & Regulatory': R.legal,

  // Recruitment & Staffing
  'Back Office & Payroll': R.hr_people,
  'Business Development': R.sales,
  'Client Management': R.sales,
  'Executive Search': R.talent,
  'Onboarding & Compliance': R.hr_people,
  'Permanent Placement': R.talent,
  'Talent Research': R.talent,
  'Technology Recruitment': R.talent,
  'Temporary & Contract': R.talent,

  // E-commerce & Marketplaces
  'Digital Marketing': R.marketing,
  'Operations & Fulfillment': R.operations,
  'Product & Technology': R.product,
  'Seller/Vendor Management': R.sales,
  'UX & Design': R.design,

  // Manufacturing & Industrial
  'EHS': R.hse,
  'Engineering': R.construction_pm,
  'HR & Industrial Relations': R.hr_people,
  'Planning & Scheduling': [
    'Production Scheduler',
    'Planning Manager',
    'Senior Planner',
    'Supply & Production Planner',
    'Other / Describe my role',
  ],
  'Process Improvement': [
    'Process Improvement Analyst',
    'Continuous Improvement Manager',
    'Lean / Six Sigma Specialist',
    'Head of Process Excellence',
    'Other / Describe my role',
  ],
  'Procurement & Supply Chain': R.procurement,
  'Quality Assurance': R.qa,

  // Food & Beverage
  'Engineering & Maintenance': R.maintenance,
  'Food Science & Innovation': [
    'Food Technologist',
    'Food Scientist',
    'R&D Manager',
    'Head of Innovation',
    'Other / Describe my role',
  ],
  'Quality & Food Safety': [
    'Quality Assurance Officer',
    'Food Safety Manager',
    'QA Manager',
    'Head of Quality & Food Safety',
    'Other / Describe my role',
  ],
  'Regulatory & Compliance': [
    'Regulatory Affairs Officer',
    'Regulatory Affairs Manager',
    'Compliance Manager',
    'Head of Regulatory',
    'Other / Describe my role',
  ],
  'Procurement & Supply': R.procurement,

  // Pharmaceutical & Drug Development
  'Clinical Affairs': R.clinical_research,
  'Clinical Research': R.clinical_research,
  'Drug Safety & Pharmacovigilance': [
    'Drug Safety Analyst',
    'Pharmacovigilance Specialist',
    'Drug Safety Manager',
    'Head of Pharmacovigilance',
    'Other / Describe my role',
  ],
  'Finance & Accounting': R.finance,
  'IT & Data': R.it_generic,
  'Medical Affairs': [
    'Medical Science Liaison',
    'Medical Advisor',
    'Senior Medical Advisor',
    'Head of Medical Affairs',
    'Other / Describe my role',
  ],
  'Operations & Manufacturing': R.operations,
  'Regulatory Affairs': R.regulatory,
  'Sales & Marketing': R.sales,

  // Generic fallback for all other departments
  'Business Development': R.sales,
  'Corporate Affairs': R.generic,
  'Customer Experience': R.customer_success,
  'HR & People & Culture': R.hr_people,
  'IT & Technology': R.it_generic,
  'Marketing & Communications': R.marketing,
  'Product': R.product,
  'Project Management': R.construction_pm,
  'Risk & Audit': [
    'Risk Analyst',
    'Internal Auditor',
    'Senior Auditor',
    'Risk Manager',
    'Head of Risk',
    'Chief Risk Officer',
    'Other / Describe my role',
  ],
  'Sales': R.sales,
  'Strategy & Transformation': R.consulting_role,
}

// ── Public API ────────────────────────────────────────────────────────────────

export function getDepartments(industry) {
  return INDUSTRY_DEPARTMENTS[industry] || GENERIC_DEPARTMENTS
}

export function getRoles(department) {
  return DEPARTMENT_ROLES[department] || R.generic
}
